name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "0 */24 * * *"

  workflow_dispatch:
  
  push:
    branches:
    - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: jacksontbailey
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#DE8302&color_dots=#F3F4F4,#99F0FF,#04D9FF,#00ADCC,#00798F
            dist/github-contribution-grid-snake-dark.svg?color_snake=#FD990D&color_dots=#002429,#005A66,#00818F,#00B8CC,#0AE7FF
      
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
